### ISSUE TITLE
Create global menu & bread crumb navigation

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#110]

**Comment by wasabideveloper** [comment]
@njordan-hsr Do you know how to pass variables to the base layout? I created a variable 'view' to show menu status and added conditions in navigation.html but variables are not passed from template to base layout.

**Comment by njordan-hsr** [comment]
I'll investigate this on the next occasion, don't know it by heart. Thanks for the information and your work on it.

**Comment by njordan-hsr** [comment]
A simple way to achieve this could be: 
http://www.djangorocks.com/snippets/getting-breadcrumbs-in-your-template.html
