### ISSUE TITLE
Where should own public excerpts be displayed?

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#114]
Should the current user's own existing public user-defined excerpts be displayed
* together with that user's private excerpts as "Personal excerpts (_&lt;username>_)"<br />or
* together with other users' public excerpts as "Public excerpts"<br />?

According to [the relevant proposed user interaction concept](https://github.com/geometalab/osmaxx/wiki/User-Interaction-Suggestion:-data-scope-selection#excerpt-selection-mode) and the [mock-up](https://github.com/geometalab/osmaxx/blob/96573678f14f399c46eb29ce5be9b8524188cadf/existing.html#L36), it'd be the former, but [currently implemented](https://github.com/geometalab/osmaxx/blob/05516672eb30c8b7a5245f334041dc32bd62f270/source/excerptexport/views.py#L47) is the latter.

**Comment by njordan-hsr** [comment]
I think we should stick with the mockup, since we lack better information for how to do it.

**Comment by das-g** [comment]
Consider that in the mockup, we have a visual indication whether an excerpt is public or not (via glyph-icons) that we don't currently have in our implementation.

I feel tempted to suggest a third solution: Have 3 optgroups:
* &lt;username>'s private excerpts
* &lt;username>'s public excerpts
* Others' public excerpts

**Comment by njordan-hsr** [comment]
I like that, let's go and do it this way.

**Comment by njordan-hsr** [comment]
Will be implemented through #124.
