### ISSUE TITLE
Style the login page using bootstrap as well

### ISSUE THREAD

**Issue by ghost** [geometalab/osmaxx#131]
Since we are using bootstrap, we should use it more consistently on the login page.

**Comment by njordan-hsr** [comment]
@wasabideveloper @das-g Is this still an issue or have we done this without noticing the issue?

**Comment by das-g** [comment]
This is still an issue, but IMHO not a severe one. It's just that the input fields and button on the login page have the default HTML styling instead of the boostrap styling like e.g. the excerpt form.
