### ISSUE TITLE
maybe: use wheel (pip7+) to release a wheel tar/zip with dependencies included

### ISSUE THREAD

**Issue by ghost** [geometalab/osmaxx#133]
See: https://lincolnloop.com/blog/fast-immutable-python-deployments/

https://pip.pypa.io/en/stable/reference/pip_wheel.html#examples

**Comment by njordan-hsr** [comment]
First step would be to add a `setup.py` for the project.

**Comment by hixi** [comment]
They way we are working currently, I think this is not going to happen - and if it does, we don't need an issue for it.
