### ISSUE TITLE
Fix osmaxx-py/src/django-stored-messages/

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#134]
"good catch, I thought I had src/ listed in .gitignore, but obviously not. Whenver a package is installed, it gets put into src/ when compiled. But it shouldn't get into that directory! Please open an issue on the tracker about this, if you can, or remind me tomorrow of cooking smth up to remedy the situation "
https://geometalab.slack.com/archives/osmaxx/p1436886431000004

**Comment by njordan-hsr** [comment]
closed by committing directly to the develop branch -> .gitignore updated.
