### ISSUE TITLE
Fix locales compilation and environment warning for development container

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#135]
# locales
root@55d8ea969302:~/source# python3 manage.py makemessages -a
CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.

# environment warning
/usr/local/lib/python3.4/dist-packages/environ/environ.py:524: UserWarning: not reading .env - it doesn't exist.
  warnings.warn("not reading %s - it doesn't exist." % env_file)
/usr/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)

@njordan-hsr: please check and fix.

**Comment by wasabideveloper** [comment]
Switch from warning to info (environment warning).

**Comment by njordan-hsr** [comment]
New docker image fixes the first issue. The second needs a look again.

**Comment by njordan-hsr** [comment]
Looks like all the warnings described above stem from a thrid-party module. I think we should be reminded that these issues exist, and fix them upstream if possible. [django-environ issue tracker](https://github.com/joke2k/django-environ/issues)
