### ISSUE TITLE
Decide how to store export options and values

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#15]
* options: available export formats and parameters
* values: Option choices of user

E.g. use settingsfile or database for parameters and use array oder entities or something for values?

**Comment by wasabideveloper** [comment]
Options: store as python dictionary in file

**Comment by wasabideveloper** [comment]
And the values? Json?

**Comment by das-g** [comment]
Available export formats (that triggered the need for this decision) should be determined by what data transformations are actually implemented. Having the 'pipelines' for different formats in separate Django apps allows operators to configure which ones they want by listing them (or not) in `INSTALLED_APPS`. Each of these pipeline apps should provide a (hard-coded) list of what export formats it enables, and the web interface should simply display all formats provided by installed apps.

**Comment by das-g** [comment]
Will be implemented by #123 (for dummy pipeline) and by all newly created piplelines.
