### ISSUE TITLE
Create data container

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#155]
Excerpt converters can not create files in 'private_media' because of not existence.

- [x] Create test creating a file and trying to download it
- [x] Create data container for this files

https://medium.com/@ramangupta/why-docker-data-containers-are-good-589b3c6c749e
http://docs.docker.com/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container
http://stackoverflow.com/questions/18496940/how-to-deal-with-persistent-storage-e-g-databases-in-docker/20652410#20652410
http://www.offermann.us/2013/12/tiny-docker-pieces-loosely-joined.html

**Comment by njordan-hsr** [comment]
See #157 for a starting point.
