### ISSUE TITLE
Implement Garmin converter chain

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#164]
![Data flow chart](https://raw.githubusercontent.com/geometalab/osmaxx-wiki-vault/master/data%20flows%20and%20tools.png)

The data converter chain will be called by the "Garmin excerpt converter" #154  .

**Estimated duration**: ~2d

**Comment by das-g** [comment]
Merged with #154.

Closing this one as duplicate.

**Comment by wasabideveloper** [comment]
@das-g It's not a duplicate! #154 is the conversion chain (data wrangling). This ( #164 ) is the python wrapper/starter.

**Comment by das-g** [comment]
@wasabideveloper we modified #154 to cover both. Even if the implementation will probably split over separate software modules, this is still a single feature / story. What subtasks will be needed will depend on implementation, so it doesn't make sense to create issues for them too far in advance.

**Comment by wasabideveloper** [comment]
:+1:
