### ISSUE TITLE
Finish administrative areas support

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#166]
- [x] ~~Check if import from polyfile is working properly~~
- [x] Add areas
- [x] Check if extraction is working properly

**Comment by das-g** [comment]
Visualization on the map is not within the scope of this story and will instead be handled in #235.

**Comment by hixi** [comment]
As discussed thoroughly with @das-g: we will be putting the countries in the conversion-service. This makes for a cleaner separation.
The polyfiles will be included in the source, and the countries will be available (_queriable_) through the rest service.
