### ISSUE TITLE
Support *.osm.pbf as export format

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#167]
Allow users to download the 'planet' file (.osm.pbf) of an extract.

**Comment by das-g** [comment]
Note: The postgis conversion currently has this file as a intermediate result.

Also note: Other future conversions might need this intermediate result, too, so it might make sense to factor this out to a separate conversion.

**Comment by hixi** [comment]
Currently, we are using extracts from `pbf` anyway, so this should be rather trivial.
