### ISSUE TITLE
Set up logging

### ISSUE THREAD

**Issue by ghost** [geometalab/osmaxx#174]
Estimated duration: ~2d

For Development and Production, setup a useful logging.

* [x] Logging for development: output all logs to docker logs.
* Logging for production:
    * [x] output all logs to docker container logs
    * [x] use a service (internal or external) to collect logs and send email in case of failures etc.

**Comment by hixi** [comment]
Maybe using a service like [rollbar](https://rollbar.com/) might be a solution?
