### ISSUE TITLE
Sort extraction options in form class

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#177]
To prevent random ordering in frontend sort the items before form generation.

Estimated duration: ~0.25d

**Comment by das-g** [comment]
Options:
- sort when reading from dictionary, to e.g. enforce alphabetic order
- use ordered dict to determine order on inserting the values

**Comment by wasabideveloper** [comment]
We already sort the options somewhere in the tests to get reproducable structures for testing. So we can take a look how we did it there...

**Comment by hixi** [comment]
since we switch to the conversion service, this is much simpler now: https://github.com/geometalab/osmaxx/pull/264/files#diff-258d56500c9813d4e043ccff95745179R4

#264 uses a tuple (and that is ordered).

Closing, please reopen, if this wasn't the problem at hand.
