### ISSUE TITLE
Enable unittest to run without docker/docker-compose

### ISSUE THREAD

**Issue by ghost** [geometalab/osmaxx#180]
Refactor the unittests, so they run on a buildserver. They usually allow a Postgres database, but no docker/docker-compose.

We still should test the interaction, but probably only using the test.sh and not using unittest (since they really are more integration tests).

**Comment by das-g** [comment]
Consider splitting non-end2end-tests into unit tests (purely within one subsystem, rest mocked if required) and subsystem integration tests (that won't be end2end but will involve collaboration of several subsystems, e.g. testing a converter in the webapp together with the respective conversion subsystem).

**Comment by hixi** [comment]
This is now possible, closing.

**Comment by das-g** [comment]
:smiley:
