### ISSUE TITLE
Make GisExcerptConverter.extract_excerpts more readable

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#186]
Estimated duration: ~0.25d

Suggestions:
- [ ] extract the `for result_file_name in os.listdir(settings.RESULT_MEDIA_ROOT):` loop into a new function (e.g. named `collect_output_files(...)`). See Pull request [comment](https://github.com/geometalab/osmaxx/pull/178/files#r38641128).

**Comment by hixi** [comment]
This code is gone with #264 , closing. Please reopen, if this needs to be addressed somewhere else now.

**Comment by das-g** [comment]
Reopening because #264 is not merged, yet. Will set up #264 to close this upon merge.
