### ISSUE TITLE
Implement frontend (client) validation

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#19]
* check for same as on server: #20 
* in case of constraint violation:
  * indicate cause (highlighting of widgets with invalid stuff / display hints / ...)
  * disable request creation button until all validations pass again

**Comment by njordan-hsr** [comment]
Maybe a good call for http://django-crispy-forms.readthedocs.org/en/latest/crispy_tag_forms.html#fundamentals -> does backend validation and basic (html5) frontend, if available.
