### ISSUE TITLE
create end-to-end test

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#190]
Test creation of extraction order - and check if the conversion completed successful.

Estimated duration: ~2d

**Comment by njordan-hsr** [comment]
We can do this at least in two ways:

* using bash/shell, and wget/curl
* using a framework like Casper or Selenium

Are there any preferences?

_Note_: Integration into the standard test suite isn't possible, since we need to start containers

**Comment by wasabideveloper** [comment]
I would prefer bash if we will do only simple tests.

**Comment by njordan-hsr** [comment]
I'd like to investigate this a bit further, bash and curl/wget is (more) complicated because of the user authentication. I think using Casper seems quite a solid solution, but I'll have to try to know ;)

**Comment by njordan-hsr** [comment]
Seems that Python 3 support is not on it's way, so abandoning this idea :disappointed:. After the discussion with @das-g and @wasabideveloper I think we should use a python script and not a bash script (and probably also using [requests library](http://www.python-requests.org/en/latest/))

**Comment by wasabideveloper** [comment]
:+1: Agree to python script.
