### ISSUE TITLE
Remove email credentials from docker compose

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#191]
Login credentials should not be stored in docker compose and published on github.

Estimated duration: ~0.5d

**Comment by njordan-hsr** [comment]
Is there a strategy to get rid of it, I mean other than removing that container and not using it, but an existing smtp (ie. from HSR)?

**Comment by wasabideveloper** [comment]
It should be the same it is about the webapp container. There should be a script in the container prompting for the credentials on setup.
**But** if the container is not reachable from outside the container forest, it is not a problem, right?

**Comment by njordan-hsr** [comment]
Yes, it _shouldn't_ be reachable from the outside, but it is some security concern nonetheless. I would welcome using an SMTP account and configuring that one using environment variables.

**Comment by wasabideveloper** [comment]
:+1:

**Comment by njordan-hsr** [comment]
@sfkeller do you know, if we might be able to use an account at the HSR for sending Mails in behalf of the osmaxx-project? (For things like `your excerpt is ready`)

**Comment by wasabideveloper** [comment]
No, we are not. I spoke to M.H. about that. That's the reason I created the gmx account (See owncloud).

**Comment by njordan-hsr** [comment]
I don't think using a gmx account is a good solution, since we _should_ have access to our own domain, after all. I'd suggest to use a project independent docker instance, ie. https://github.com/catatnight/docker-postfix.

**Comment by wasabideveloper** [comment]
:+1:
