### ISSUE TITLE
Fix empty extraction data of GIS excerpt converter (feature count zero for all layers)

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#196]
## Examples exhibiting this problem:

* http://<i>&lt;test server domain></i>/downloads/2973ee96-4fa1-41a1-bdeb-d1eb319dd238/
* http://<i>&lt;test server domain></i>/downloads/0eb97801-dd1e-4e7a-b797-f52e0c2d1a80/
* http://<i>&lt;test server domain></i>/downloads/6d529c7a-93ce-4a42-9def-6259e3451701/

## To reproduce:
* Extract a **non-empty** area
* Download the result
* Extract the `data` folder an view it in QGIS

### Expected:
* Some layers have a non-zero feature count.

### Observed
* All layers have feature count `0`.

Estimated duration: ~4d.

**Comment by njordan-hsr** [comment]
Is this an error on our side or is it an error in the osmaxx-osm2psql-converter-chain?

**Comment by njordan-hsr** [comment]
I tried reproducing this issue, but can't. 
There have been some changes in the [osmaxx-postgis-conversion](https://github.com/geometalab/osmaxx-postgis-conversion) repository, might that actually have fixed this issue?
If not, can someone provide an example (ie. coordinates or similar), which exposes the described behaviour?

**Comment by njordan-hsr** [comment]
I'm closing this issue, if somebody can reproduce this, please reopen with some description of reproducing the issue.

**Comment by njordan-hsr** [comment]
Reopening, since we use the wrong coordinate sequence. Hotfix.

**Comment by das-g** [comment]
Fixed from hotfix branch merged with bef19c5d300ad852655b927574fb050b4f274c39. Fix confirmed on online test installation:
* http://<i>&lt;test server domain></i>/downloads/0e85bed9-62a1-464f-82e9-b1629e947c74/
* http://<i>&lt;test server domain></i>/downloads/84a30a36-8c8c-455a-a5b3-42a0f0c96487/
* http://<i>&lt;test server domain></i>/downloads/d3b3d955-34c0-4db4-afe2-7ed413fa5300/

Closing as fixed.
