### ISSUE TITLE
Release version & deploy release to staging environment

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#197]
Time estimate: ~1d

- [x] Release https://github.com/geometalab/osmaxx-postgis-conversion/milestones/Alpha%202%20-%20Refactoring%20&%20file-gdb
- [x] Test local production setup manually (DevOp Smoketest)
- [x] Test user workflow of production locally (User Smoketest)
- [x] Release new version
- [x] Deploy to staging server, build containers and run using docker-compose

**Comment by njordan-hsr** [comment]
Released and deployed 0.6.
