### ISSUE TITLE
Create form to request access

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#200]
Estimated duration: ~1.5d

See
#182 
https://github.com/geometalab/osmaxx/commit/c4817c37c49128393077fb8b2e16111c8231b795#commitcomment-13307969

Replace the user_manager_username by a group. Prompt this group assignment on creation of the superuser.

**Comment by das-g** [comment]
Access request form should only be shown to logged in users without access.

Is a form needed at all? (If the user is logged in, we already got his clavid account name, and there's nothing more we need to decide whether a user should be given access.) The access request could therefore be triggered simply by creating a clavid-based osmaxx account, without further action from the user's side.
