### ISSUE TITLE
Refactor excerpt converter "contract"

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#216]
Estimated duration: ~3d

- [ ] Move NAME, EXPORT_FORMATS and EXPORT_OPTIONS to an options file (one for each converter inside the module): Maybe we should use https://docs.python.org/3.4/library/configparser.html
- [ ] Remove module_converter_configuration function by a module property for each converter
- [ ] Create a test searching all converters and checking the "contract" -> existence of NAME, EXPORT_FORMATS, EXPORT_OPTIONS, converter_configuration, execute
- [ ] Document how to add a new converter

**Comment by njordan-hsr** [comment]
It might even warrant the use of a [ConfigParser](https://docs.python.org/3.4/library/configparser.html), lets look into that as soon as we start this issue.

**Comment by das-g** [comment]
If the values of those constants is specific to individual modules (the converters), why move the constant definition to somewhere else?

**Comment by wasabideveloper** [comment]
We won't move the constant's somewhere else:
:open_file_folder: excerptconverter
  - :open_file_folder:  gisexcerptconverter
    - :page_facing_up: gis_excerpt_converter.py
    - :page_facing_up: options.py
    - :page_facing_up: tests.py
  - :file_folder:  dymmyexcerptconverter
    - :page_facing_up: dummy_excerpt_converter.py
    - :page_facing_up: options.py
    - :page_facing_up: tests.py
  - :page_facing_up: converter_manager.py
  - :page_facing_up: converter_helper.py
  tests.py

**Comment by das-g** [comment]
Obsolete by introduction of conversion service.
