### ISSUE TITLE
Update internal wiki

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#219]
Estimated duration: ~0.25d

General: **Remove as much topics as possible**. Otherwise employ someone to update this information weekly :wink: to prevent outdated information.

- [x] Remove dead link to "Projekt Tracker"
- [x] Remove jenkins link
- [x] Remove Landing page link
- [x] Link team to http://giswiki.hsr.ch/Osmaxx#Project
- [x] Update Tasks &rarr; Better: remove the tasks and use a task tracker. Tasks here will always be outdated.
- [x] Update dates/milestones
- [x] Remove oder update "Entwurf/Technologien"
- [x] Add link to deployment chapter of the osmaxx application in server wiki page
  - [x] Move deployment information from owncloud to that chapter

**Comment by wasabideveloper** [comment]
@sfkeller Will you update the internal wiki or should we?

**Comment by sfkeller** [comment]
I'll leave it up to you :-)

**Comment by wasabideveloper** [comment]
On your own risk ;-) I will remove all outdated content.

**Comment by wasabideveloper** [comment]
@das-g Please take a look.

**Comment by das-g** [comment]
Made some more adaption. Hope it's alright for now.

Closing.
