### ISSUE TITLE
Refactor gis excerpt converter to use an instance instead procedural method chaining

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#220]
- [ ] Create an instance of a GisExcerptConverter class on execute
- [ ] Setup the whole temporary environment on construct
  - [ ] Get order from database
  - [ ] Create result directory
  - [ ] Generate docker-compose file
- [ ] Split conversion process in smaller methods
- [ ] Cleanup the whole temporary environment on destruct
  - [ ] Cleanup result directory
  - [ ] Cleanup containers

**Comment by hixi** [comment]
Obsolete, since we handle the conversion in a separate service.
