### ISSUE TITLE
show version number somewhere on the web application

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#228]
As a tech-savvy user, I'd like to know what version of Osmaxx is running on an installation I'm looking at over the web, so that I can
* include this information in bugs I report
* look up what known issues this version has (according to bugs reported by others)
* know what features I can expect (by comparing with milestones and releases on GitHub)

As a developer, I'd like to know what version of Osmaxx is running on an installation I'm looking at, so I can tell whether a scheduled deployment has actually been performed.

In either case, I want to be able to determine this version number without having to access the server backend (e.g. by SSH). Requiring accessing the web backend (`/admin` URL) is acceptable, but would be unfortunate. Optimal would be not even requiring to be logged in.

**Comment by das-g** [comment]
If the implementation hard-codes the version number somewhere in the source code, mention in [`docs/git-repository.md` **Todo on release**](https://github.com/geometalab/osmaxx/blob/develop/docs/git-repository.md#todo-on-release) that (and where in the source) the version must be bumped.

**Comment by njordan-hsr** [comment]
So `Update version number under osmaxx-py/osmaxx/__init__.py` isn't enough? It's not on this bunch of commits, that might be a bit misleading, since that was an online edit on the develop branch.

**Comment by das-g** [comment]
Oh, didn't see that.
