### ISSUE TITLE
Show confirmation page after successfull creation of export request

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#23]

**Comment by njordan-hsr** [comment]
Can be achieved using the default (read: integrated in the core) Django: https://docs.djangoproject.com/en/1.8/ref/contrib/messages/

**Comment by das-g** [comment]
- [ ] create a page that
  - tells the user that their request was received
  - whether the requested export is already being processed
  - that they'll receive an email once processing is done and downloads are available
  - what address that email will be sent to
- [ ] redirect the `POST` request to a `GET` of that page
