### ISSUE TITLE
Show polygon-based excerpt boundaries on map

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#235]
As a user creating a new export order from an existing excerpt, I'd like to see the selected excerpt's boundary on the map, no matter whether it is a user-created excerpt (bounding box) or a predefined administrative area (polygon).

**Comment by hixi** [comment]
depends on #235

**Comment by das-g** [comment]
> depends on #235

depends on itself?

**Comment by hixi** [comment]
Ouch, dependency would have been the other way around, #299 depends on this story, but that one is closed already, so not changing anything here.

**Comment by hixi** [comment]
Closing, since #317 provides this.
