### ISSUE TITLE
Webapp: React on status change callback

### ISSUE THREAD

**Issue by ghost** [geometalab/osmaxx#247]
on status update (i.e. when callback received)
- [x] use url from payload to request current status for the respective format (depends on #257)
- [x] update own status in database
    - [x] if changed: notify user (within web UI)
-  when status == finished
    - [x] retrieve file for respective format (use URL from status request answer) (retry if necessary?)
    - [ ] ~~request file deletion on other side if retrieval was successful (use URL from status request answer)~~ (tracked by #279 , #139 and #289 )
- when all formats of order have a final status (finished or error)
    - [x] notify user (by email)

**Comment by das-g** [comment]
Depends on depends on #257
