### ISSUE TITLE
Implement Status Update Worker

### ISSUE THREAD

**Issue by ghost** [geometalab/osmaxx#250]
When a status change occurs in the RQ queue:
- [ ] updates the status in the django-rest-api database
- [ ] call the appropriate callback

TBD: Should this status update worker
- poll the queue [scheduled by RQ](https://github.com/ui/rq-scheduler) to check for new status updates (which RQ jobs write to the queue by default, anyway)<br />or
- be a job enqueued by the conversion jobs<br />or
- another solution?

**Comment by hixi** [comment]
We opted for another solution, is now implemented, obsolete issue.
