### ISSUE TITLE
conversion-service: check whether the DB is up

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#260]
The ping-based check at https://github.com/geometalab/osmaxx-postgis-conversion/blob/ec00ce314b960a860b3042d7d1551283002b3649/conversion_service/entrypoint.sh#L10 stopped working with docker 1.5 and was/will be replaced or augmented with a hardcoded wait.

- [ ] ~~get rid of the hardcoded wait again and check in the loop weather the DB is really up. (E.g. by connecting with `psql`)~~

**Comment by hixi** [comment]
Not needed anymore, works as advertised again. Closing.
