### ISSUE TITLE
When should old conversion results be removed?

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#27]
* After 1 week?

**Comment by njordan-hsr** [comment]
For such tasks, celery heartbeat can be used.

**Comment by wasabideveloper** [comment]
May be the excerpt/user manager should be able to configure this in the backend?

**Comment by wasabideveloper** [comment]
Decided: Will be put in settings.py (Maybe container environment variable). Should be adjusted during deployment.
