### ISSUE TITLE
Add tests for the right url

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx#291]
For the [small bug](https://github.com/geometalab/osmaxx-postgis-conversion/commit/8b89d5cb4eb59470b60f74557e89736fe5c3cbaf), there should be some more serious test catching assuring the correct url is built.

**Comment by das-g** [comment]
If the URL is different, `ConversionTest.test_convert_with_host_and_job_assembles_url_correctly()` already fails. What more is wanted here?

**Comment by hixi** [comment]
You're right, [the test](https://github.com/geometalab/osmaxx-postgis-conversion/commit/8b89d5cb4eb59470b60f74557e89736fe5c3cbaf#diff-d84a54aae8c8d5ce88fdc7ffaed1793bR76) already covers what was wanted here.
