### ISSUE TITLE
get rid of EnumField

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#295]

**Comment by hixi** [comment]
This probably already happened by accident. Closing, reopen if it isn't the case.

**Comment by das-g** [comment]
[Still in `requirements.txt` on branch `combine_repos`](https://github.com/geometalab/osmaxx-frontend/blob/2292b0d08ece35d13c255af06b082d8590f038a6/requirements.txt#L6) and used for [`ExtractionOrder#state`](https://github.com/geometalab/osmaxx-frontend/blob/2292b0d08ece35d13c255af06b082d8590f038a6/osmaxx/excerptexport/models/extraction_order.py#L50). **&rarr;&nbsp;Reopening**

That field can probably be removed, though. State is now tracked on `Export`s.

**Comment by hixi** [comment]
Has been removed by other pull-request(s) from source, closing.
