### ISSUE TITLE
Don't send emails on behalf of FROM addresses we don't own

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#298]
We [are sending emails on behalf of the user](https://github.com/geometalab/osmaxx/blob/49ce929de03b6a696fb8e4ea2f4c0b30d219b911/osmaxx-py/osmaxx/excerptexport/views.py#L175) (i.e., with their email address as `FROM` header). We send these emails to ourselves (thus urgency low), but still:
~~If we want to continue to send email on behalf of addresses we don't own, [we should at least also set the `SENDER` header](http://stackoverflow.com/a/18906678/674064) to an address we _do_ own. (And for which our server is seen as a legitimate email message source (tracked in #300).)~~
We should use a `FROM` address we own for sending email.

**Comment by hixi** [comment]
Thinking about this, I strongly disagree: We should not be sending emails in behalf of the user at all, but include the email of the user in the message and send it with the specified user. 

On production, the current behaviour is likely to fail, using a smtp provider to send emails often disallows sending emails from arbitrary email-addresses.

**Comment by das-g** [comment]
> On production, the current behaviour is likely to fail, using a smtp provider to send emails often disallows sending emails from arbitrary email-addresses.

Having a non-arbitrary email address as `SENDER` mitigates this in some cases (depending on the applicable policies). It's what other services that legitimately send or forward emails (e.g. mailing lists) do, too.

But I'm not advocating we keep sending emails with arbitrary `FROM` addresses. That's why I wrote
> **If** we want to continue to send email on behalf of addresses we don't own, [...]

**Comment by das-g** [comment]
Edited title and description to reflect way forward.
