### ISSUE TITLE
Make sure the emails our application sends have a chance to arrive

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#300]
For our production setup, implement as much of the stuff of http://blog.codinghorror.com/so-youd-like-to-send-some-email-through-code/ as we can.

**Comment by hixi** [comment]
I disagree on this as a must-have:

- very much work for little gain
- we don't send emails low level
- we use an external smtp server (which we don't control)
- we use Django's internal send_mail which delivers an error message to sentry if email sending should've failed


achieving a certain degree of security at deploytime can be quite simple:
- send an email to a specified email (maybe by deploy-script input?) while deploying

If we _were_ a shop, where we loose customers if we're not sending emails, this might be a must-have, but for informing the user only about the progress, I don't see the benefit of having a massive check overhead.

**Comment by das-g** [comment]
I wasn't aware we'll be using our organization's mail server for sending and only have our application be an SMTP client to that server, not to the final recipient's server. If that's the case, this is in fact not a must-have.
