### ISSUE TITLE
MultiValueDictKeyError: "'status'"

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#301]
https://sentry.dev.njo.ch/geometalab/osmaxx-dev/group/15/

```
MultiValueDictKeyError: "'status'"
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "osmaxx/job_progress/views.py", line 8, in tracker
    order.progress_url = request.GET['status']
  File "django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
```

**Comment by das-g** [comment]
That call should come from https://github.com/geometalab/osmaxx-postgis-conversion/blob/cee76016e798a428f0a4901c5c17e79124fd080e/conversion_service/worker/converter_job.py#L58

Could `self.status_url` have been `None`?

**Comment by das-g** [comment]
Eh, I guess I must use [the `params` instead of the `data` argument](http://docs.python-requests.org/en/latest/user/quickstart/#passing-parameters-in-urls).

**Comment by hixi** [comment]
Yes, that is the correct answer to that issue ;-)

**Comment by hixi** [comment]
I think I fixed it somewhere along the way, maybe even merged into develop already? Should we do a redeploy?

**Comment by hixi** [comment]
This is fixed in develop, closing.

**Comment by das-g** [comment]
re-opening to add a test that would have caught this
