### ISSUE TITLE
Have on-page notifications about order progress change display status name, not status ID

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#309]
"Extraction order &lt;order number> **is now 3.**" isn't meaningful to the user.

![... is now 3](https://cloud.githubusercontent.com/assets/97746/11767217/d4e19264-a1a6-11e5-99a0-7df87e10fca0.png)

**Comment by hixi** [comment]
and yet another reason to use Django default choices style and not our own enums...
