### ISSUE TITLE
Split forms into two separate forms to remove complexity.

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#320]
Forms:
* Order an existing excerpt or a country
  * Select for existing excerpts or countries
  * Map (readonly) to show excerpt bounds or countries
  * Extraction options
* Order a new excerpt
  * Input fields for new excerpt
  * Map to edit the excerpt bounds
  * Extraction options

All the form mode handling can be removed. The validation and map will no longer need to handle two modes.

**Comment by hixi** [comment]
instead of reinventing the wheel, would it make sense to use [parsley](http://parsleyjs.org/)?

**Comment by wasabideveloper** [comment]
Maybe, but I'm not sure. The most complexity inside the validation script are the relations between states of elements, the form mode switcher and some really osmaxx specific contraints. I checked the list of built in validators. There are no usable built in validators for us. So we need to implement a custom validator function for every filed. And this is the solution we already have...

**Comment by hixi** [comment]
I'm fine with sticking with the current solution and keeping an eye open if we should do a lot more, to possibly switch to a library.

**Comment by wasabideveloper** [comment]
If we simplify the forms it makes sense to try to integrate parsley.

**Comment by wasabideveloper** [comment]
I tried parsley and it does not really simplify our script:
* We still need to listen all the events of the form elements and call parsley by hand because parsley only listens the submit button in standard configuration
* The only win we got was the select boxes
* There seems to be a bug. I didn't get parsley working properly. It never allowed to submit the form :smirk: 
* We won't get less of code

**Comment by hixi** [comment]
Thank you for investigating!
