### ISSUE TITLE
conversion-service: export data in WGS 84

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#335]
Even though the [requested](https://github.com/geometalab/osmaxx/blob/9f6423ff25fa4aba71b3901fccb693b120657e60/web_frontend/osmaxx/excerptexport/forms/temporary_form_helper.py#L16) and [requestable](https://github.com/geometalab/osmaxx-postgis-conversion/blob/18c0a36dbe083035f868e64f381713c99eaf5492/conversion_service/conversion_job/models.py#L66) CRS is currently hardcoded to WGS 84 (a.k.a. EPSG:4326), the data in the resulting downloads is in one of the Pseudo Mercator projections (can't tell whether EPSG:3785 or EPSG:3857).

### To reproduce
 1. In QGIS with OpenLayers Plugin installed and active, display OpenStreetMap tiles. (In QGIS 2.10, go to menu `Web` > `OpenLayers plugin` > `OpenStreetMap` > `OpenStreetMap`.)
 2. Create a download with osmaxx for any GIS format (i.e., anyone that is not a garmin `IMG`)
 3. Unpack that data and load its `road_l_any` layer in QGIS
    * make sure it's displayed above the OpenStreetMap tiles
 4. Make sure the road layer's CRS is set to 'Popular Visualisation CRS / Mercator' (EPSG:3785). (That's what was set automatically when I tried this.)

##### Expected
Roads in layer don't spatially match those of the base map.

##### Observed
Roads in layer do spatially match those of the base map.

#### Further experiments:
* Set the layer CRS to 'WGS 84 / Pseudo Mercator' (EPSG:3857)

    ##### Expected
    Roads in layer don't spatially match those of the base map.

    ##### Observed
   Roads in layer do spatially match those of the base map.

* Set the layer CRS to 'WGS 84' (EPSG:4326)

    ##### Expected
    Roads in layer do spatially match those of the base map.

    ##### Observed
    Roads in layer don't spatially match those of the base map.

Mentioned CRS hardcoding will be eliminated in #331, which might implicitly fix this bug.

**Comment by hixi** [comment]
This is currently the case and will stay this way until #331 is implemented, since we ignore this setting completely (AFAIK we always have!). I'd rather close this, since this wasn't a bug so far, from a user perspective and apparently the layers are being treated in the right way. There is a reason why we have opened #331 as a feature.
