### ISSUE TITLE
define interface for data conversion status to inform Django

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#34]
* Error handling
* Success
* Progress / status

Data conversion processes are not required to actively trigger actions in Django. Probably the interface can be files written by the data conversion and read by Django as needed (on user request).

**Comment by das-g** [comment]
Nicola recommends using http://www.celeryproject.org/

**Comment by wasabideveloper** [comment]
Proposal for data conversion service call params: https://github.com/geometalab/osmaxx/wiki/Interfaces-&-Notifications, discussed with @eugenepjk .
