### ISSUE TITLE
Replace location filter by bbox for existing excerpts

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#342]
Location filter is only used for editing. So we can remove the location filter library for the existing excerpt view and show a rectangle on the map like we show a polygon on the map for countries.

**Comment by das-g** [comment]
I kinda like that one can (ab?)use the current behavior to create new bbox excerpts from existing ones. Of course, this could also be provided differently, e.g. via a link that would take you to the create-new-excerpt page with bbox boundaries pre-initialized to the values of an existing one.
