### ISSUE TITLE
Implement mail notification upon export request completion

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#35]
As a **export requester**, I want to **be informed** when my downloads are ready, so I can go get them.

**Comment by njordan-hsr** [comment]
I suggest doing this in two steps:
* [ ] Implement "Sending an email when finished after the export succeeded"
* [ ] Implement "Sending an error email when an error occurred"

For Development, I'd just print the mails into the log of the container, on production we either need sendmail or a SMTP Server connection (User/Password).

Generally: is `no-reply@osmaxx.hsr.ch` a good choice as sender for this email?
