### ISSUE TITLE
Fix new (BBox) excerpt form for MS IE

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#363]
# To reproduce
1. click button "New excerpt'
2. select reasonably small area on map (e.g., zoom in, then click button 'Select area within current zoom')

## expected
* all 4 coordinate value form fields are filled accordingly
* size is computed

## observed
* only 'north' coordinate form field is filled
* size is displayed as 'too large' independent of bbox size

Issue created based on mail from Benjamin:

> Beim Auszug eines neuen Excerpts schreibt die Anwendung die Bounding box Begrenzung (Lat oder Long) nicht mehr automatisch heraus. Bei einer manuellen Eingabe funktioniert es einwandfrei.
Das Problem ist besteht übrigens nur im IE. Mit Firefox klappt es ebenfalls einwandfrei. Auch die Angabe wieviele % der Auszug zu gross ist wird nur im Firefox korrekt angezeigt.
Nur als kleiner Hinweis.

**Comment by das-g** [comment]
hint from @wasabideveloper: IE (even still in version 11) uses `fireEvent()` instead `dispatchEvent()`.

**Comment by hixi** [comment]
Issue found: IE doesn't support the [Event constructor](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event)

**Comment by hixi** [comment]
Found a possible solution: http://www.lessanvaezi.com/filter-select-list-options/

**Comment by wasabideveloper** [comment]
@hixi ?! The solution is already implemented: https://github.com/geometalab/osmaxx/blob/feature/%23363-fix-new-bbox-excerpt-form-MS-IE-11/web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/excerpt_filter.js . There is only a bug with IE.

**Comment by hixi** [comment]
No, this doesn't use show and hide, so it doesn't use the one thing IE doesn't support...
