### ISSUE TITLE
Fully adopt (new) pip-tools

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#407]
### One-off:
- [ ] [Identify top-level dependencies and put them into `requirements.in`](http://nvie.com/posts/better-package-management/#virtue-1-declare-only-your-top-level-dependencies) (and `*-requirements.in`, if we want test and/or dev requirements to be separate)
- [ ] Re-generate `requirements.txt` (and `*-requirements.txt`) from `*.in` using `pip-compile`
- [ ] Check all those into Git

### Regularly
Establish a fixed schedule for the following:
- [ ] Re-generate `requirements.txt` (and `*-requirements.txt`) from `*.in` using `pip-compile`
- [ ] Check all those into Git

#### Schedule suggestions:
- fixed interval<br />or
- every time you start a branch that targets being merged into `master` (typically git-flow **release** branches and git-flow **hotfix** branches.)

## Changes recommended for everyone's  individual workflow
- instead of `pip install -r requirements.txt`, use `pip-sync`

**Comment by hixi** [comment]
I'm unsure if this really is something worth spending time on; for me the current workflow with the requirements.txt file works very well.
