### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#44]
Visualize data flow concept

**Comment by wasabideveloper** [comment]
Where should i put it? GitHub Wiki? Directory "documentation" in repo?

**Comment by das-g** [comment]
GitHub [repo wiki of geometalab/osmaxx](https://github.com/geometalab/osmaxx/wiki), I'd say.

GitHub doesn't seem to serve image files checked into the repo wiki git repo `https://github.com/geometalab/osmaxx.wiki.git`, so I've put them into a [separate repo](https://github.com/geometalab/osmaxx-wiki-vault), so I could use them on the wiki. (See https://github.com/geometalab/osmaxx/wiki/User-Interaction-Suggestion:-data-scope-selection#map-in-bounding-box-definition-mode for an example.)

**Comment by das-g** [comment]
@sfkeller Please find the new diagrams at https://github.com/geometalab/osmaxx/wiki/Architecture

**Comment by das-g** [comment]
@sfkeller Is [this](https://github.com/geometalab/osmaxx/wiki/Architecture#used-tools-and-the-data-flows-between-them) more like what you were looking for?
