### ISSUE TITLE
Use UUID as public identifier for downloads

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#49]
Replace self created identifiers with uuids:
https://docs.python.org/2/library/uuid.html

**Comment by njordan-hsr** [comment]
Starting with Django 1.8 there will be a native UUIDField in [Django](https://docs.djangoproject.com/en/1.8/ref/models/fields/#uuidfield) -> we should probably switch!
See #80 and #81

**Comment by wasabideveloper** [comment]
Agree.
