### ISSUE TITLE
Move and delete repos

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx#532]
move:
- geometalab/osmaxx to geometalab/osmaxx-tmp
- move geometalab/osmaxx-frontend to geometalab/osmaxx

remove:
- geometalab/osmaxx-tmp
- geometalab/osmaxx-conversion-service

update:
- documentation
- release procedure

**Comment by das-g** [comment]
> remove:
> - geometalab/osmaxx-tmp

Don't forget to transfer its wiki to `geometalab/osmaxx-docs`, first! See geometalab/osmaxx-docs#42
