### ISSUE TITLE
Export language-specific names

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#546]
While the `SELECT INTO` queries for layers with common attributes fill in
* `name_en`
* `name_fr`
* `name_es`
* `name_de`
* `name_int`

, the `VIEW`s actually responsible for the export are missing these columns, with exception of the `VIEW` for the newly added `transport_l`. (The attributes `name` and `label` seem to be consistently exported, though.)

If I remember correctly, these attributes should be exported, too. (If not, they should be removed from the [list of 'common attributes'](https://github.com/geometalab/osmaxx/blob/develop/docs/osmaxx_data_schema.md#common-attributes) in the documentation.)

**Comment by das-g** [comment]
> If I remember correctly, [attributes `name_en`, `name_fr`, `name_es`, `name_de`, `int_name`] should be exported, too.

@sfkeller, @geoSLG, do I remember correctly?

**Comment by das-g** [comment]
Huh, and what about the `name_intl` (not to be confused with `name_int` (without trailing `l` in the attribute name)) documented in https://github.com/geometalab/osmaxx-docs/blob/develop/documentation.md#common-attributes? We never had that and I can't remember that it was planned or even discussed to have something like that.

@sfkeller, @geoSLG Is an attribute wanted that works very similar to `label`, only slightly different?

Fallback cascade for `label`:
* **value of OSM tag `name` (if already in Latin script)**
* value of OSM tag `name:en`
* value of OSM tag `name:fr`
* value of OSM tag `name:es`
* value of OSM tag `name:de`
* **transliterated value of OSM tag `name`**

Fallback cascade for `name_intl` according to [current documentation](https://github.com/geometalab/osmaxx-docs/blob/af5b4704bc2ab840e3092d40e8ee429f99053aff/documentation.md#common-attributes):
* value of OSM tag `name:en`
* **value of OSM tag `int_name`**
* value of OSM tag `name:fr`
* value of OSM tag `name:es`
* value of OSM tag `name:de`
* **value of OSM tag `name` (untransliterated, whether or not already in latin script)**

(Differences betwenn the two cascades highlighted in **bold**.)

**Comment by hixi** [comment]
@sfkeller Can you provide your opinion on this issue?

**Comment by geoSLG** [comment]
Name:int oder name:intl sind interessant und es würde evtl Sinn machen diese ebenfalls einzubauen. ich kanns aber nicht wirklich beurteilen, da ich auch nicht weiss wie oft dieser benutzt wird. Falls Name:intl leer ist, würde dann halt einfach französisch, spanisch usw. genommen. Also wenns kein grosser Aufwand ist. Würde ich sagen man könnte es implementieren.

Lieber Gruss

Bene

**Comment by sfkeller** [comment]
Attribute `name_intl` is not needed. Remove it.

Attribute label should be modified as follows:


Fallback cascade for `label`:
* value of OSM tag `name` (if already in Latin script)
* value of OSM tag `name:en`
* value of OSM tag `name:fr`
* value of OSM tag `name:es`
* value of OSM tag `name:de`
* **transliterated value of OSM tag `int_name`**
* transliterated value of OSM tag `name`
