### ISSUE TITLE
Redirect all successful POST requests to GET actions

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#56]
prevent back button reposting

Expected duration: ~2d.

**Comment by wasabideveloper** [comment]
* login
* extraction order creation

**Comment by njordan-hsr** [comment]
Also remove the `request['Refresh']` silliness.

https://github.com/geometalab/osmaxx/blob/bac4f6fc590f59ac3d4cd3aa4940ad27818438ce/osmaxx-py/osmaxx/excerptexport/views.py#L113
