### ISSUE TITLE
How should OSMaxx be used by "external" people?

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx#579]
Decide between:
- Use two different instances, one for the public, another for our customer
- Use Prioritized Queues for different User Groups (and some dedicated workers for the elevated user groups' queue(s))

**Comment by hixi** [comment]
When the Issues #663, #661 and #664 are completed, we can adjust more or less any day to which ever variant we would like. @sfkeller @das-g Is it OK to close this?

**Comment by das-g** [comment]
> Is it OK to close this?

Yes, unless we need the issue as a reminder to discuss the operation strategy going forward.
