### ISSUE TITLE
include schema documentation PDF in result downloads ZIP archives

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#586]

**Comment by hixi** [comment]
We're not providing the schema-documentation as a pdf, because pdf generation looks very ugly. Should we either include a link to the corresponding "about_us"-page/github-page or include the markdown file directly?

**Comment by das-g** [comment]
The HTML looked alright, only the PDF was garbage. The advantage of including it with the download is that it will match the schema version from when the export was made (modulo mistakes and omissions in the documentation, obviously). Including a permalink to the matching online revision would be possible but cumbersome.
