### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#60]
http://choosealicense.com/
@sfkeller, @das-g proposal MIT http://choosealicense.com/licenses/mit/

**Comment by das-g** [comment]
Although I do not condone swearing, I would prefer the [WTFPL](http://www.wtfpl.net/about/), combined with a separate warranty disclaimer [as suggested in their FAQ](http://www.wtfpl.net/faq/). It's fully compatible for relicensing under the MIT license (or under any license for that matter), so anyone who doesn't like the WTFPL would be free to do that.
