### ISSUE TITLE
Refresh hint on "My Exports" page

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#634]
optionally with link or button that does the refreshing when clicked.

Alternatively, let that page auto-refresh.

(Requested by @sfkeller)

**Comment by hixi** [comment]
auto-refresh is a very, very annoying feature, speaking from a usability POV.

You can click on the title called `My Exports` to reload the page ^^ - every browser already has a reload button, no need to add one on the page (exception on mobile).

Adding a note would be a good idea, I think.
