### ISSUE TITLE
Review METADATA.txt

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#636]
[Current `METADATA.txt`](https://github.com/geometalab/osmaxx/blob/develop/osmaxx/conversion/converters/converter_gis/static/METADATA.txt) is completely static and probably partially outdated.

Let's go through it together to decide what still makes sense, what needs to be parametrized and what should be replaced or removed.

**Comment by das-g** [comment]
Let's also decide in what (natural) language the information in that file should be. Currently it's a mixture of English and German.

**Comment by hixi** [comment]
@sfkeller How about just removing this file altogether?

**Comment by hixi** [comment]
Closing after Review and adaptations.
