### ISSUE TITLE
Make "water" layers more consistent

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#651]
* The documentation of [`water_a`](https://github.com/geometalab/osmaxx/blob/a4c496a97105fff7630992b5d2c29ba4c6f8cf8a/docs/osmaxx_data_schema.md#water_a) and [`water_p`](https://github.com/geometalab/osmaxx/blob/a4c496a97105fff7630992b5d2c29ba4c6f8cf8a/docs/osmaxx_data_schema.md#water_p) explicitly lists `man_made=pier` and `man_made=reservoir_covered` ~~when the SQL logic actually copies the value any **arbitrary** `man_made=*` (unless `natural=*` or `leisure=*`).~~
* [`water_p`](https://github.com/geometalab/osmaxx/blob/a4c496a97105fff7630992b5d2c29ba4c6f8cf8a/docs/osmaxx_data_schema.md#water_p) lists `man_made=pier` twice (for `type` values `pier` and `lock_gate`) ~~although the logic actually just copies the `man_made=*` value~~.

For other OSMaxx layers, we only copy verbatim OSM tag values to attribute `type` after having checked the values with a whitelist, so that the `type` attribute has a well-defined range.

* The names of the [SQL scripts](https://github.com/geometalab/osmaxx/tree/a4c496a97105fff7630992b5d2c29ba4c6f8cf8a/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/water) probably shouldn't end in `insert_table`. (Those for other layers don't.)
* The name of the `water_p` insertion SQL script should contain `water_p`, not `water_b`

**Comment by sfkeller** [comment]
Use a whitelist instead of the current implementation.

**Comment by das-g** [comment]
> [T]he SQL logic actually copies the value any **arbitrary** `man_made=*` (unless `natural=*` or `leisure=*`).

I was wrong about this: `man_made` can only be one of few selected values, due to [the `WHERE` clauses in `010_water_a.sql`](https://github.com/geometalab/osmaxx/blob/ba0b254e2e8370d18d4f6aa18693ccde708b906d/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/water/010_water_a.sql#L35), `020_water_p.sql` ([1](https://github.com/geometalab/osmaxx/blob/ba0b254e2e8370d18d4f6aa18693ccde708b906d/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/water/020_water_p.sql#L32), [2](https://github.com/geometalab/osmaxx/blob/ba0b254e2e8370d18d4f6aa18693ccde708b906d/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/water/020_water_p.sql#L67)) and [`030_water_l.sql`](https://github.com/geometalab/osmaxx/blob/ba0b254e2e8370d18d4f6aa18693ccde708b906d/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/water/030_water_l.sql#L45), so a whitelist approach is already in use.
