### ISSUE TITLE
name relevant OSM tag values for tunnel and bridge recognition in documentation

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#659]
[The OSMaxx schema documentation indicates](https://github.com/geometalab/osmaxx/blame/c106869a50b20c64ec2d388fff7cf4d0a62bfc5a/docs/osmaxx_data_schema.md#L1089) that the value of the `bridge` and `tunnel` attributes in the OSMaxx output schema depend on the OSM tags `bridge=yes`, `bridge=no`, `tunnel=yes` and `tunnel=no`, when actually, we treat `bridge` OSM tag values `split_log`, `beam`, `culvert`, `low_water_crossing`, `yes`, `suspension`, `viaduct`, `aqueduct` and `covered` as bridges and absence of the `bridge` tag and any other values as not a bridge. (See [roads](https://github.com/geometalab/osmaxx/blob/c106869a50b20c64ec2d388fff7cf4d0a62bfc5a/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/road/010_road.sql#L55), [railways](https://github.com/geometalab/osmaxx/blob/c106869a50b20c64ec2d388fff7cf4d0a62bfc5a/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/railway/010_railway.sql#L33), [aerialways](https://github.com/geometalab/osmaxx/blob/c106869a50b20c64ec2d388fff7cf4d0a62bfc5a/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/railway/020_aerialway.sql#L34).)

The same goes for tunnes with [`yes`/`no`](https://github.com/geometalab/osmaxx/blame/c106869a50b20c64ec2d388fff7cf4d0a62bfc5a/docs/osmaxx_data_schema.md#L1098) vs. [`passage`, `culvert`, `noiseprotection galerie`, `gallery`, `building_passage`, `avalanche_protector`,`teilweise`, `viaduct`, `tunnel` and `yes`](https://github.com/geometalab/osmaxx/blob/c106869a50b20c64ec2d388fff7cf4d0a62bfc5a/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/road/010_road.sql#L60).

**Comment by sfkeller** [comment]
Suggestion: Refer to the code in the documentation, so we don't have to duplicate the list of positively treated values.

**Comment by das-g** [comment]
> Suggestion: Refer to the code in the documentation, so we don't have to duplicate the list of positively treated values.

I considered that, but as the explicit documentation also gives us a nice OSM tag &rarr; OSMaxx layer/attribute mapping, I opted to spell it out rather than just referring to the respective code sections.
