### ISSUE TITLE
Should labels be based on the name tag for addresses, too?

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#690]
For the layers with [common attributes](https://github.com/geometalab/osmaxx/blob/develop/docs/osmaxx_data_schema.md#common-attributes), the value of the `label` column/attribute [is taken from the `name=*` OSM tag or one of the language-specific `name:<lang>=*` OSM tags](https://github.com/geometalab/osmaxx/blob/70481603d1f29de1c8b1bf083777aa1b06d795ca/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/address/010_address.sql#L26). While this makes sense for most of these layers, I doubt this is very useful for `address_p`, as many entries in that layer will miss all of these OSM tags.

Should the `label` logic for `address_p` remain as-is or should the name(s) be combined with or replaced by content from the `addr:*=*` OSM tags? (At least house numbers as a fallback would be useful in the labels, I think.)

**Comment by sfkeller** [comment]
Let's just display the few but perhaps important names in attribute label. 
Regarding housenumbers (as part of a complete address) I wouldn't display them for now. 
I hope there will be a separate project which exclusively deals with address extraction from OSM.

**Comment by das-g** [comment]
So we'll keep the `label` attribute logic for `address_p` as-is. Closing.

(Styles (in QGIS or ArcGIS etc.) might still use attributes other than `label` for the actual labeling, depending on the map's purpose.)
