### ISSUE TITLE
More welcoming landing page ("home" page)

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#742]
Ideas (combinable):
* Two **BIG** buttons, somewhat centered:
  * "Export existing excerpt or country"
  * "Create and export new excerpt"
* Spiffy tagline that captures what sets OSMaxx apart from similar projects
* Icons and short texts outlining features/aspects of OSMaxx
* Icons and short texts for software on/with which OSMaxx is build (PostgreSQL & PostGIS, Docker (& used images/Linux distros), Django, Django restframework, GDAL/OGR, mkgmap, py.test, Python 3, ...)

**Comment by das-g** [comment]
Here's a sketch of how this could look:

![sketch_osmaxx_landing_page20161116_135538](https://cloud.githubusercontent.com/assets/97746/20348246/cf5cbf62-ac04-11e6-857d-967677c43814.jpg)

* Suggested OSMaxx tagline:

    > ### Get the OpenStreetMap data you want in the file formats you need

    ### Explanation
    (will not be displayed to the user)

    > Get the OpenStreetMap data you want [...]

    In contrast to e.g. http://download.geofabrik.de/ , users can define their own excerpts to be exported

    > [...] in the file formats you need

    Again in contrast to e.g. http://download.geofabrik.de/ , the users don't have to use PBF but can choose any or all of 4 GIS formats and one navigation device format.
* Suggestions for features & aspects to point out:
 * open data:

    > [<img title='open data inside logo' src='http://www.opendatainside.com/wp-content/themes/odi/img/logo_odi.png' width='200'>](http://opendatainside.com/)
    > Use freely under terms of the [ODbL](http://opendatacommons.org/licenses/odbl/summary/)
 * advertise our schema(-mapping):

    > sophisticated mapping from OSM's tag-based "schema-less schema" to GIS-compatible layer-based schema
 * OSM as data source:

    > [<img title='OSM logo' src='http://wiki.openstreetmap.org/w/images/7/79/Public-images-osm_logo.svg' width='200'>](http://wiki.openstreetmap.org/wiki/Logos)
    > Based on current OpenStreetMap data
    > 
    > The most comprehensive community-driven geodata collection

    (Is the latter claim true? I just made that up, but I assume it might fit.)
 * Garmin IMG export available
 * another aspect of our output schema:

    > 33 thematic layers suitable for your GIS
 * file formats

    > Choose between 3 GIS formats
 * OSMaxx is FLOSS, build on/from existing FLOSS:

    > [<img title='OSI logo' src='https://opensource.org/files/osi_symbol.png' width='200'>](https://opensource.org/logo-usage-guidelines#The_Symbol)
    > Free/libre software built from open source components
* To not clutter the landing page too much, I would put logos of the software projects used on a separate page.

**Comment by das-g** [comment]
> * Suggested OSMaxx tagline:
> 
>     > ### Get the OpenStreetMap data you want in the file formats you need

Let's make that

> ### Get the OpenStreetMap data you want in the file format you need

(singular)

**Comment by das-g** [comment]
Which one looks better?

![screenshot from 2016-11-23 16-25-38](https://cloud.githubusercontent.com/assets/97746/20567590/8d6ba8bc-b199-11e6-9f63-3756d4925de0.png)

vs.

![screenshot from 2016-11-23 16-24-37](https://cloud.githubusercontent.com/assets/97746/20567591/8d6de488-b199-11e6-8655-1e7c14a94c17.png)

(Alternative suggestions for button labeling welcome.)

**Comment by sfkeller** [comment]
First one, since the two choices visually keep same (blue) space and are evenly distributed.
