### ISSUE TITLE
Make Short Video (due before 15.12.2016)

### ISSUE THREAD

**Issue by sfkeller** [geometalab/osmaxx#749]
Make video as screencast on how to use OSMaxx together with QGIS in order to create a background map or city plan.
Publish result on youtube in IFS channel (https://www.youtube.com/user/InstituteForSoftware )

**Comment by das-g** [comment]
I've started a script [on the wiki](https://github.com/geometalab/osmaxx/wiki/script-for-demo-video)

**Comment by das-g** [comment]
Done: https://www.youtube.com/playlist?list=PLIAMSR28-EsZjNjFPi5Avt4gryOU8w1j2
