### ISSUE TITLE
Add HTML metadata (thumb nail etc.) on Homepage for Social Media

### ISSUE THREAD

**Issue by sfkeller** [geometalab/osmaxx#750]
See https://giswiki.hsr.ch/Best_Practices_for_Web_Maps#Metadata_for_Social_Media

**Comment by das-g** [comment]
@sfkeller Can you test https://osmaxx.hsr.ch/ on http://developers.facebook.com/tools/lint/ ? For some reason FB seems to require an account to access their validator and I don't want one.

**Comment by das-g** [comment]
We need absolute URLs with HTTPS scheme to satisfy [FB's Open Graph validator](http://developers.facebook.com/tools/lint/). Re-opening.

(`request.build_absolute_uri` from 419aeb1f5d5bbbd169ba9092fcd49977dd3d9485 produces HTTP URLs because we let nginx instead of django provide HTTPS.)
