### ISSUE TITLE
Access requests still incoming

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#775]
The user administration email address is still receiving access request messages from time to time. This must mean that some users are still being led to the page with the "request access" button.

We want to grant access to anyone with an OSM account, if they provide a valid email address (for notification about finished exports), without any manual steps on our part.

**Comment by sfkeller** [comment]
Related to #780 .
(Note: Currently, user lands on page "Access Request" when email is not yet confirmed).
