### ISSUE TITLE
ugly links in homepage footer

### ISSUE THREAD

**Issue by sfkeller** [geometalab/osmaxx#800]
1a. There are some broken SVG images in footer of homepage.
1b. And homepage seems to have problems fitting page to screen (there's a vertical scroll bar appearing at my 16:8 laptop screen 1600x900).
2. While correcting this, pls. add social media metadata for Twitter card and Facebook image: See https://giswiki.hsr.ch/Best_Practices_for_Web_Maps#Metadata_for_Social_Media

**Comment by das-g** [comment]
>  1b. And homepage seems to have problems fitting page to screen (there's a vertical scroll bar appearing at my 16:8 laptop screen 1600x900).

I thought we already had an issue about that, but only found #688

>  2. While correcting this, pls. add social media metadata for Twitter card and Facebook image: See https://giswiki.hsr.ch/Best_Practices_for_Web_Maps#Metadata_for_Social_Media

Already tracked in #750

**Comment by das-g** [comment]
> 1a. There are some broken SVG images in footer of homepage.

Not quite sure what you mean here, @sfkeller. The footer has links to the SVG files of the emblems used in the page's body (to conform with the "BY" part of "CC BY-SA"), but shouldn't (and as far as I can see doesn't) embed any SVG images there. The links don't seem to be broken.

If you're seeing something else, can you give a more precise description and maybe some screenshots?

**Comment by sfkeller** [comment]
I see. The copyright text very long. The link style stands out unnecessary. Pls. take out at least "emblem" of the link text and replace it with word "icons".
