### ISSUE TITLE
Decide structure for resources

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#9]
consider Django conventions

**Comment by wasabideveloper** [comment]
Proposal:

| Resource of osmaxx.tld | Application part / View | access |
|--- |--- |--- |
| / | Osmaxx welcome page/Overview (links to downloads, new excerpts, ...), current /excerptexport | protected (user login) |
| /downloads | Download overview (list of excerpt export requests and its available downloads), current /excerptexport/downloads | protected (user login) |
| /downloads/{downloadUUID} | Ships single file for download | public |
| /export<br />&nbsp;&nbsp;#existing<br />&nbsp;&nbsp;#create | &bull; Excerpt creation view, default shown view part "use existing excerpts"<br />&nbsp;&nbsp;&sdot; Use existing excerpts view part<br />&nbsp;&nbsp;&sdot; Create new excerpt view part | protected (user login) |
| /request/{excerptExportRequestId} | Status of export request | protected (user login) |
| /request/{excerptExportRequestId}/notify | Notification api? | protected (api key)

**Comment by das-g** [comment]
Looks good to me.

**Comment by das-g** [comment]
@njordan-hsr what do you think?

**Comment by njordan-hsr** [comment]
Generally I think this is a good way for structuring the urls.
I have a couple of remarks (as always ;-) )
* Should the home, aka `/`, really be protected? Wouldn't it make more sense, from a user's perspective, to display a default view if anonymous, and offer all the possibilities when logged in?
* Is export and order the correct for the user action?
    * excerpt_export or excerpt 
    * order_status or export_status
Maybe there we can come up with even better names, but generally I like this.

**Comment by das-g** [comment]
Hmm ... I just now noticed: `/export#existing` and `/export#create` would be misleading, as this is **not** about whether an *existing export* will be used or a *new export* created. It's about whether a new or existing **excerpt** is exported.

So maybe `/export#an-existing-excerpt` and `/export#a-new-excerpt` would be clearer? (That a new excerpt will have to be 'created' to be exported is IMHO an implementation detail the user doesn't need to worry about.)

**Comment by wasabideveloper** [comment]
@das-g You are right. That's much clearer for the user.
@njordan-hsr It make sense not to protect `/` and showing a login mask and links to the download page and new extraction order page. But the other resources (excluding a specific download) should be protected. There is no sense to see these resources without login because it will be blank (no existing excerpts without login, no downloads, no status of my last extraction orders, ... cause of the missing user relation).

I improved consistency of the names and worked in your proposals.

I moved the new proposal to wiki: https://github.com/geometalab/osmaxx/wiki/Resources---URL-structure. Please take a look.
