### ISSUE TITLE
Extractions are not correct

### ISSUE THREAD

**Issue by Tuvoc** [geometalab/osmaxx#909]
I have experienced recently, that extractions are not correct any more .
Data fragments from all over the world are fuesed together in one file geodatabase. 
attached a screenshot with data points  from an extraction from the city of Mombasa/Kenia

![datapoints](https://user-images.githubusercontent.com/73273520/96833556-f07b3180-1440-11eb-9b7d-31b88ba991b8.PNG)

**Comment by das-g** [comment]
Hi Tuvoc

Thanks for the report. I suspect this is the same problem as #908, so I'm closing this issue as a duplicate.
