### ISSUE TITLE
Set CSP headers

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#95]
https://en.wikipedia.org/wiki/Content_Security_Policy
https://www.owasp.org/index.php/Content_Security_Policy

**Comment by njordan-hsr** [comment]
What does this provide on top of Django normal security model (escaping, [csrf protection](https://docs.djangoproject.com/en/1.8/ref/csrf/))?

**Comment by wasabideveloper** [comment]
It's an additional level of security on client side. Django may have security issues or maybe we missuse features like raw encoding because we didn't know how to do it better.

**Comment by njordan-hsr** [comment]
If I understood this correctly, it doesn't provide really anything (for us): we would need to add a header to allow JavaScript and HTML, but have no security benefit. I'd argue, this can either be left out or as `nice to have`; if we should decide to do this, it could either be a custom [Middleware](https://docs.djangoproject.com/en/1.8/topics/http/middleware/), or as [nginx](http://nginx.org/en/docs/http/ngx_http_headers_module.html)/[apache](http://httpd.apache.org/docs/2.2/mod/mod_headers.html#header) [nginx-header](https://gist.github.com/plentz/6737338#file-nginx-conf-L57)/[apache-header](https://github.com/h5bp/server-configs-apache/blob/e603554f559b1be4861553239e22a7844075bedc/src/security/content-security-policy.conf) directly

**Comment by njordan-hsr** [comment]
After discussion, we agreed that this should be done. How it should be done:
* Document setting the correct headers with nginx/appache, since the requests for static-media are not going through Django
* Provide an example deployment config for nginx

New issue for implementation will be opened after further discussion and this issue should remain open until then.

**Comment by hixi** [comment]
Changed: we are using whitenoise, so this issue needs an update.

**Comment by hixi** [comment]
We have a nginx-frontend with a specialized configuration, so this could actually be added.
