### ISSUE TITLE
Use X-Send of Apache/nginx to provide download file

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#96]
Instead of streaming file by django

- for nginx: http://wiki.nginx.org/XSendfile
- Do not expose internal file path!

**Comment by njordan-hsr** [comment]
IMHO this is not needed regarding the size and complexity of the project. We should remember to use some more workers (ie. `gunicorn -w 20 ...`) though, so we don't block when multiple downloads are in progress simultaneously.

**Comment by hixi** [comment]
Closing, not necessary to over-complicate things. If we discover that this _really_ is an issue, we can reopen this issue anytime.

**Comment by wasabideveloper** [comment]
:heavy_check_mark: I agree. I propose to reopen the issue as type:idea for future.
